//! Generated `graphics.library` LVO (library vector offset) metadata table.
//!
//! # Provenance
//!
//! Derived from AROS's `graphics.library` interface description
//! (`rom/graphics/graphics.conf`, the `##begin functionlist` block AROS's own build
//! generates the `.sfd`/`.fd` files from -- see `tools/gen_lvos.py` for
//! why this repo reads the `.conf` directly rather than a generated `.sfd`).
//!
//! - Source URL: <https://raw.githubusercontent.com/aros-development-team/AROS/05c3f84db3844f8b68b9d2c3ea264a42700c4ae0/rom/graphics/graphics.conf>
//! - Source commit: 05c3f84db3844f8b68b9d2c3ea264a42700c4ae0
//! - Generated: 2026-08-27
//! - Generator: `tools/gen_lvos.py`
//!
//! Only uncopyrightable interface facts were extracted from the source --
//! function names, LVO offsets, and argument-register assignments -- as
//! bare data; no descriptive text, comments, or file structure from the
//! source was copied. This file is licensed under the same terms as the
//! rest of this repository: MIT OR Apache-2.0.
//!
//! DO NOT EDIT BY HAND. Regenerate with `tools/gen_lvos.py`.

use crate::cpu::{AddressRegister, DataRegister};
use crate::lvos::{ArgReg, LvoEntry};

/// The full `graphics.library` LVO table (all known functions, not just the
/// ones this runtime currently implements handlers for -- this way
/// unknown-call diagnostics can print a real function name for any of
/// them, not just the handful we emulate).
pub static GRAPHICS_LVOS: &[LvoEntry] = &[
    LvoEntry {
        name: "BltBitMap",
        lvo: -30,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
            ArgReg::D(DataRegister(6)),
            ArgReg::D(DataRegister(7)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "BltTemplate",
        lvo: -36,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ClearEOL",
        lvo: -42,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ClearScreen",
        lvo: -48,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "TextLength",
        lvo: -54,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "Text",
        lvo: -60,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetFont",
        lvo: -66,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "OpenFont",
        lvo: -72,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "CloseFont",
        lvo: -78,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AskSoftStyle",
        lvo: -84,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "SetSoftStyle",
        lvo: -90,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AddBob",
        lvo: -96,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AddVSprite",
        lvo: -102,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "DoCollision",
        lvo: -108,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "DrawGList",
        lvo: -114,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "InitGels",
        lvo: -120,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "InitMasks",
        lvo: -126,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "RemIBob",
        lvo: -132,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "RemVSprite",
        lvo: -138,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetCollision",
        lvo: -144,
        args: &[
            ArgReg::D(DataRegister(0)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SortGList",
        lvo: -150,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AddAnimOb",
        lvo: -156,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "Animate",
        lvo: -162,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "GetGBuffers",
        lvo: -168,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "InitGMasks",
        lvo: -174,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "DrawEllipse",
        lvo: -180,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AreaEllipse",
        lvo: -186,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "LoadRGB4",
        lvo: -192,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "InitRastPort",
        lvo: -198,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "InitVPort",
        lvo: -204,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "MrgCop",
        lvo: -210,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "MakeVPort",
        lvo: -216,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "LoadView",
        lvo: -222,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "WaitBlit",
        lvo: -228,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "SetRast",
        lvo: -234,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "Move",
        lvo: -240,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "Draw",
        lvo: -246,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AreaMove",
        lvo: -252,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AreaDraw",
        lvo: -258,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AreaEnd",
        lvo: -264,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "WaitTOF",
        lvo: -270,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "QBlit",
        lvo: -276,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "InitArea",
        lvo: -282,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetRGB4",
        lvo: -288,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "QBSBlit",
        lvo: -294,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "BltClear",
        lvo: -300,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "RectFill",
        lvo: -306,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "BltPattern",
        lvo: -312,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ReadPixel",
        lvo: -318,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "WritePixel",
        lvo: -324,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "Flood",
        lvo: -330,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "PolyDraw",
        lvo: -336,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::A(AddressRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetAPen",
        lvo: -342,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetBPen",
        lvo: -348,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetDrMd",
        lvo: -354,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "InitView",
        lvo: -360,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "CBump",
        lvo: -366,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "CMove",
        lvo: -372,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "CWait",
        lvo: -378,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "VBeamPos",
        lvo: -384,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "InitBitMap",
        lvo: -390,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ScrollRaster",
        lvo: -396,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
        ],
        private: false,
    },
    LvoEntry {
        name: "WaitBOVP",
        lvo: -402,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetSprite",
        lvo: -408,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeSprite",
        lvo: -414,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ChangeSprite",
        lvo: -420,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "MoveSprite",
        lvo: -426,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "LockLayerRom",
        lvo: -432,
        args: &[ArgReg::A(AddressRegister(5))],
        private: false,
    },
    LvoEntry {
        name: "UnlockLayerRom",
        lvo: -438,
        args: &[ArgReg::A(AddressRegister(5))],
        private: false,
    },
    LvoEntry {
        name: "SyncSBitMap",
        lvo: -444,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "CopySBitMap",
        lvo: -450,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "OwnBlitter",
        lvo: -456,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "DisownBlitter",
        lvo: -462,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "InitTmpRas",
        lvo: -468,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AskFont",
        lvo: -474,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "AddFont",
        lvo: -480,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "RemFont",
        lvo: -486,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AllocRaster",
        lvo: -492,
        args: &[ArgReg::D(DataRegister(0)), ArgReg::D(DataRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "FreeRaster",
        lvo: -498,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AndRectRegion",
        lvo: -504,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "OrRectRegion",
        lvo: -510,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "NewRegion",
        lvo: -516,
        args: &[],
        private: false,
    },
    LvoEntry {
        name: "ClearRectRegion",
        lvo: -522,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ClearRegion",
        lvo: -528,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "DisposeRegion",
        lvo: -534,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeVPortCopLists",
        lvo: -540,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeCopList",
        lvo: -546,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ClipBlit",
        lvo: -552,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
            ArgReg::D(DataRegister(6)),
        ],
        private: false,
    },
    LvoEntry {
        name: "XorRectRegion",
        lvo: -558,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "FreeCprList",
        lvo: -564,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetColorMap",
        lvo: -570,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeColorMap",
        lvo: -576,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetRGB4",
        lvo: -582,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ScrollVPort",
        lvo: -588,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "UCopperListInit",
        lvo: -594,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeGBuffers",
        lvo: -600,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "BltBitMapRastPort",
        lvo: -606,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
            ArgReg::D(DataRegister(6)),
        ],
        private: false,
    },
    LvoEntry {
        name: "OrRegionRegion",
        lvo: -612,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "XorRegionRegion",
        lvo: -618,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AndRegionRegion",
        lvo: -624,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "SetRGB4CM",
        lvo: -630,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "BltMaskBitMapRastPort",
        lvo: -636,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
            ArgReg::D(DataRegister(6)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AddDisplayDriverA",
        lvo: -642,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetDisplayDriverCallback",
        lvo: -648,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AttemptLockLayerRom",
        lvo: -654,
        args: &[ArgReg::A(AddressRegister(5))],
        private: false,
    },
    LvoEntry {
        name: "GfxNew",
        lvo: -660,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GfxFree",
        lvo: -666,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GfxAssociate",
        lvo: -672,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "BitMapScale",
        lvo: -678,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ScalerDiv",
        lvo: -684,
        args: &[
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "TextExtent",
        lvo: -690,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "TextFit",
        lvo: -696,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(3)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "GfxLookUp",
        lvo: -702,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "VideoControl",
        lvo: -708,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "OpenMonitor",
        lvo: -714,
        args: &[ArgReg::A(AddressRegister(1)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "CloseMonitor",
        lvo: -720,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FindDisplayInfo",
        lvo: -726,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "NextDisplayInfo",
        lvo: -732,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "AddDisplayData",
        lvo: -738,
        args: &[ArgReg::A(AddressRegister(0))],
        private: true,
    },
    LvoEntry {
        name: "AddDisplayInfoData",
        lvo: -744,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: true,
    },
    LvoEntry {
        name: "SetDisplayInfoData",
        lvo: -750,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: true,
    },
    LvoEntry {
        name: "GetDisplayInfoData",
        lvo: -756,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "FontExtent",
        lvo: -762,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ReadPixelLine8",
        lvo: -768,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "WritePixelLine8",
        lvo: -774,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ReadPixelArray8",
        lvo: -780,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "WritePixelArray8",
        lvo: -786,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "GetVPModeID",
        lvo: -792,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ModeNotAvailable",
        lvo: -798,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "WeighTAMatch",
        lvo: -804,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "EraseRect",
        lvo: -810,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ExtendFont",
        lvo: -816,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "StripFont",
        lvo: -822,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "CalcIVG",
        lvo: -828,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AttachPalExtra",
        lvo: -834,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ObtainBestPenA",
        lvo: -840,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetRGB32",
        lvo: -852,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "GetAPen",
        lvo: -858,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetBPen",
        lvo: -864,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetDrMd",
        lvo: -870,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetOutlinePen",
        lvo: -876,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "LoadRGB32",
        lvo: -882,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "SetChipRev",
        lvo: -888,
        args: &[ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetABPenDrMd",
        lvo: -894,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "GetRGB32",
        lvo: -900,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AllocBitMap",
        lvo: -918,
        args: &[
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::A(AddressRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "FreeBitMap",
        lvo: -924,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "GetExtSpriteA",
        lvo: -930,
        args: &[ArgReg::A(AddressRegister(2)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "CoerceMode",
        lvo: -936,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ChangeVPBitMap",
        lvo: -942,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ReleasePen",
        lvo: -948,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "ObtainPen",
        lvo: -954,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
        ],
        private: false,
    },
    LvoEntry {
        name: "GetBitMapAttr",
        lvo: -960,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AllocDBufInfo",
        lvo: -966,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "FreeDBufInfo",
        lvo: -972,
        args: &[ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "SetOutlinePen",
        lvo: -978,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetWriteMask",
        lvo: -984,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetMaxPen",
        lvo: -990,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::D(DataRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "SetRGB32CM",
        lvo: -996,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ScrollRasterBF",
        lvo: -1002,
        args: &[
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
        ],
        private: false,
    },
    LvoEntry {
        name: "FindColor",
        lvo: -1008,
        args: &[
            ArgReg::A(AddressRegister(3)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AllocSpriteDataA",
        lvo: -1020,
        args: &[ArgReg::A(AddressRegister(2)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ChangeExtSpriteA",
        lvo: -1026,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(3)),
        ],
        private: false,
    },
    LvoEntry {
        name: "FreeSpriteData",
        lvo: -1032,
        args: &[ArgReg::A(AddressRegister(2))],
        private: false,
    },
    LvoEntry {
        name: "SetRPAttrsA",
        lvo: -1038,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "GetRPAttrsA",
        lvo: -1044,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "BestModeIDA",
        lvo: -1050,
        args: &[ArgReg::A(AddressRegister(0))],
        private: false,
    },
    LvoEntry {
        name: "WriteChunkyPixels",
        lvo: -1056,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::D(DataRegister(4)),
        ],
        private: false,
    },
    LvoEntry {
        name: "SetRegion",
        lvo: -1086,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ClearRegionRegion",
        lvo: -1092,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AreRegionsEqual",
        lvo: -1098,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "IsPointInRegion",
        lvo: -1104,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "ScrollRegion",
        lvo: -1110,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
        ],
        private: false,
    },
    LvoEntry {
        name: "AndRectRegionND",
        lvo: -1116,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "AndRegionRegionND",
        lvo: -1122,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "OrRectRegionND",
        lvo: -1128,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "OrRegionRegionND",
        lvo: -1134,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "XorRectRegionND",
        lvo: -1140,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "XorRegionRegionND",
        lvo: -1146,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ClearRectRegionND",
        lvo: -1152,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "ClearRegionRegionND",
        lvo: -1158,
        args: &[ArgReg::A(AddressRegister(0)), ArgReg::A(AddressRegister(1))],
        private: false,
    },
    LvoEntry {
        name: "WritePixels8",
        lvo: -1182,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::D(DataRegister(5)),
        ],
        private: false,
    },
    LvoEntry {
        name: "FillRectPenDrMd",
        lvo: -1188,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
            ArgReg::D(DataRegister(4)),
            ArgReg::D(DataRegister(5)),
            ArgReg::D(DataRegister(6)),
        ],
        private: false,
    },
    LvoEntry {
        name: "DoRenderFunc",
        lvo: -1194,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::A(AddressRegister(3)),
            ArgReg::A(AddressRegister(4)),
            ArgReg::D(DataRegister(0)),
        ],
        private: false,
    },
    LvoEntry {
        name: "DoPixelFunc",
        lvo: -1200,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::A(AddressRegister(1)),
            ArgReg::A(AddressRegister(2)),
            ArgReg::D(DataRegister(2)),
        ],
        private: false,
    },
    LvoEntry {
        name: "UpdateBitMap",
        lvo: -1206,
        args: &[
            ArgReg::A(AddressRegister(0)),
            ArgReg::D(DataRegister(0)),
            ArgReg::D(DataRegister(1)),
            ArgReg::D(DataRegister(2)),
            ArgReg::D(DataRegister(3)),
        ],
        private: false,
    },
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lvos::find_by_name;

    // Sanity-check a handful of well-known LVOs against published AmigaOS
    // graphics.library values (see docs/plan.md's T7/T12 entries).
    #[test]
    fn known_lvos_match_amigaos() {
        let cases: &[(&str, i32)] = &[("OpenFont", -72), ("CloseFont", -78)];
        for (name, lvo) in cases {
            let entry = find_by_name(GRAPHICS_LVOS, name)
                .unwrap_or_else(|| panic!("missing LVO entry for {name}"));
            assert_eq!(entry.lvo, *lvo, "{name} LVO mismatch");
        }
    }
}
