//! LVO (library vector offset) metadata tables and lookup helpers.
//!
//! AmigaOS libraries are called through a base pointer plus a small
//! negative offset (the LVO) into a per-library jump table -- see the
//! module docs on [`crate::dispatch`] for how this runtime fakes that
//! mechanism. Handlers registered with [`crate::dispatch::LibraryTable::
//! register`] need to know each function's LVO and, ideally, its
//! argument-register calling convention; unknown-call diagnostics want the
//! same data in reverse (offset -> name) so they can name the function a
//! guest program tried to call instead of just printing a raw number.
//!
//! [`LvoEntry`] is the per-function record; concrete tables (one per
//! emulated library) live in submodules like [`dos`], generated by
//! `tools/gen_lvos.py` from an AROS interface description -- see that
//! script's module doc and `docs/plan.md`'s "fd/SFD metadata decision"
//! section for why AROS was chosen as the source and what is and isn't
//! copied from it.

use crate::cpu::{AddressRegister, DataRegister};

pub mod dos;
pub mod exec;
pub mod locale;
pub mod mathffp;
pub mod mathieeedoubbas;
pub mod mathieeedoubtrans;
pub mod mathtrans;
pub mod utility;

/// One argument register in a library call's calling convention: either a
/// data register (D0-D7) or an address register (A0-A7), reusing
/// [`crate::cpu::DataRegister`]/[`crate::cpu::AddressRegister`] so this
/// stays interchangeable with the rest of the CPU abstraction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArgReg {
    /// A data register argument (D0-D7).
    D(DataRegister),
    /// An address register argument (A0-A7).
    A(AddressRegister),
}

/// One entry in a generated LVO metadata table: a function's name, its
/// LVO (library vector offset, always `<= 0`), and its argument registers
/// in call order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LvoEntry {
    /// The function's name, e.g. `"PutStr"`.
    pub name: &'static str,
    /// The library vector offset: `jsr LVO(a6)` calls this function. Always
    /// negative (or zero, for the never-used LVO 0 slot, which no real
    /// table entry occupies).
    pub lvo: i32,
    /// Argument registers in call order.
    pub args: &'static [ArgReg],
    /// Whether the source interface description marks this as a private
    /// vector (not meant to be called by guest code directly via LVO --
    /// e.g. `dos.library`'s `OpenLib`/`CloseLib`, which real programs
    /// reach via `exec.library`'s `OpenLibrary`/`CloseLibrary` instead).
    /// Kept (not dropped) so bias-consuming slots stay accounted for and
    /// diagnostics can still name them; callers that only want the public
    /// ABI can filter on this field.
    pub private: bool,
}

/// Looks up a table entry by function name (exact match).
pub fn find_by_name<'a>(table: &'a [LvoEntry], name: &str) -> Option<&'a LvoEntry> {
    table.iter().find(|e| e.name == name)
}

/// Looks up a table entry by LVO offset (exact match). Used to turn a raw
/// offset from an unknown-call diagnostic back into a function name.
pub fn find_by_lvo(table: &[LvoEntry], lvo: i32) -> Option<&LvoEntry> {
    table.iter().find(|e| e.lvo == lvo)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn find_by_name_and_lvo_round_trip() {
        let entry = find_by_name(dos::DOS_LVOS, "Lock").expect("Lock should be in the table");
        assert_eq!(entry.lvo, -84);
        let back = find_by_lvo(dos::DOS_LVOS, -84).expect("looking up -84 should find Lock");
        assert_eq!(back.name, "Lock");
    }

    #[test]
    fn find_by_name_missing_is_none() {
        assert!(find_by_name(dos::DOS_LVOS, "NotARealFunction").is_none());
    }

    #[test]
    fn find_by_lvo_missing_is_none() {
        assert!(find_by_lvo(dos::DOS_LVOS, 12345).is_none());
    }

    #[test]
    fn utility_find_by_name_and_lvo_round_trip() {
        let entry = find_by_name(utility::UTILITY_LVOS, "FindTagItem")
            .expect("FindTagItem should be in the table");
        assert_eq!(entry.lvo, -30);
        let back = find_by_lvo(utility::UTILITY_LVOS, -30)
            .expect("looking up -30 should find FindTagItem");
        assert_eq!(back.name, "FindTagItem");
    }

    #[test]
    fn utility_find_by_name_missing_is_none() {
        assert!(find_by_name(utility::UTILITY_LVOS, "NotARealFunction").is_none());
    }
}
