#!/usr/bin/env python3
"""Compares volamos against `vamos` using amitools' *own* test corpus
(`test/bin`/`test/suite`/`test/data` in an external amitools checkout,
e.g. `~/src/amitools`), rather than volamos's own hand-written fixtures
(that's `tools/compare_vamos.py`).

## Why a separate corpus from `compare_vamos.py`

amitools ships ~40 small real C programs, each pre-built with up to
four real Amiga compilers (`test/bin/<name>_<flavor>[_dbg]`: gcc, SAS/C
(`sc`), vbcc (`vc`), agcc), a `pytest` suite (`test/suite/*.py`) pinning
down each one's exact invocation and expected output, and checked-in
ground-truth output files (`test/data/*.txt`) for several. Multiple
real compilers' differing startup/calling conventions have found real
bugs in this project before (the `exectest` A6-convention issue --
`docs/plan.md`), so this is a meaningfully different, larger corpus
than volamos's own ~6 fixtures, not just more of the same.

## Licensing: local-only, external checkout, never bundled

amitools is GPLv2; volamos is MIT/Apache-2.0. Nothing under `test/src`,
`test/bin`, or `test/data` is ever copied into this repo -- `--amitools-checkout`
must point at an already-existing local checkout (there is no default;
unlike `--volamos`'s own `target/release/volamos`, there's no sensible
default for an external GPL checkout). Same posture
`tools/compare_three_way.py` already uses for its own external,
never-bundled assets (a proprietary AmiBake corpus and a Kickstart ROM
image) -- see that script's own module doc. This script is local-only
for the same reason: promoting it into CI (`tools/compare_vamos.py`'s
own `compare` job) is a plausible, separate future step once the
initial entries below are proven, not part of this first cut.

## Explicit, identical volume config per entry -- not either engine's
## own defaults

volamos (since issue #43) and `vamos`'s own test suite (via its
`test.vamosrc`) each install a *different* default `sys:` skeleton by
design -- `vamos`'s test suite assigns `sys:` to its own `ram:` auto-
volume, producing `c`/`s`/`libs`/`devs`/`t` subdirectories through
`vamos`'s own auto-assign machinery; volamos's own defaults produce a
persistent `SYS:` with `envarc`/`env` added and `t` living under `RAM:`
instead. Reconciling those two independent "zero-config" mechanisms
isn't the point of this harness -- each `CORPUS` entry instead supplies
the *same* explicit `-V`/`-a` flags to both engines, sidestepping
either side's own defaults entirely.

## Usage

    python3 tools/compare_amitools_suite.py --amitools-checkout ~/src/amitools

Exits non-zero if any corpus entry not fully explained by
`KNOWN_DIVERGENCES` disagrees between volamos and `vamos`, or (for an
entry with a `test/data/*.txt` ground-truth file) if either engine
disagrees with that checked-in expected output -- a stronger check than
two-engine agreement alone, which would miss a bug both sides happen to
share. **Caveat**: amitools' own `test/data/*.txt` files are themselves
generated by capturing a `vamos` run (`test/helper/runner.py`'s
`--gen-data` mode), not independently verified against real hardware --
so for a case where volamos and `vamos` disagree and the `.txt` file
sides with `vamos`, that's still really just "agrees with vamos", one
data point, not two.

## Corpus (initial; see this module's own "explicitly deferred" note in
## `docs/plan.md`'s matching entry for what's intentionally not here yet
## -- companion-binary-building entries, other compiler flavors, and CI
## promotion)

The first run against this initial 5-entry corpus already found three
real volamos bugs (issues #45, #46, #47 -- all still visible `FAIL`s
below, `KNOWN_DIVERGENCES` is reserved for divergences attributed to
`vamos`, not for volamos's own unfixed ones) and two things needing
further investigation (#48, #49) -- concrete evidence this corpus finds
things volamos's own ~6 fixtures don't.

- `dos_match`: `MatchFirst`/`MatchNext`/`ap_Buf` via a real `AnchorPath`
  scan of a scratch `SYS:` -- exercises `crate::dosanchor`.
- `dos_seek`: `Open(MODE_NEWFILE)`/`Write`/`Seek`/`Read`/`IoErr` round
  trip against a scratch `TEST:` volume -- fully self-contained (the
  program creates its own file).
- `util_date`, `vprintf`, `exec_rawdofmt`: no volume needed at all;
  compared three-way against their checked-in `test/data/*.txt`.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parent.parent

FLAVOR = "gcc"

# fixture (corpus-entry) name -> (reason, issue URL). Same convention as
# compare_vamos.py's KNOWN_DIVERGENCES -- reserved for divergences
# attributed to vamos (or genuinely unresolved pending real-hardware
# verification), never for volamos's own unfixed bugs, which should stay
# visible FAILs until fixed (see dos_match/dos_seek/exec_rawdofmt below,
# each with its own open volamos-side issue).
KNOWN_DIVERGENCES: dict[str, tuple[str, str]] = {
    "util_date": (
        "utility.library/CheckDate's own NDK autodoc documents 'the wday "
        "field ... is not checked' as a real historical AmigaOS bug -- "
        "volamos matches that; vamos validates wday anyway. Also affected "
        "by the %x hex-digit-case question below.",
        "https://github.com/sidick/volamos/issues/49",
    ),
    "vprintf": (
        "%x/%lx hex digit case differs (volamos: lowercase, vamos: "
        "uppercase) -- no NDK autodoc pins this down; genuinely needs "
        "real-hardware (Copperline) verification, not assumed either way.",
        "https://github.com/sidick/volamos/issues/48",
    ),
}


@dataclass
class Entry:
    name: str
    guest_args: list[str]
    # Returns the extra -V/-a flags (identical for both engines) this
    # entry needs, given a fresh scratch directory; None if the entry
    # needs no volume/assign at all.
    setup: Callable[[Path], list[str]] | None
    # Exact expected stdout lines (order matters, no normalization
    # applied) when known ahead of time from test/suite/<name>.py
    # itself; None when comparison instead reads test/data/<name>.txt
    # (see `data_file`).
    expected: list[str] | None = None
    # Basename of a checked-in ground-truth file under test/data/, for
    # a three-way comparison instead of (or in addition to) `expected`.
    data_file: str | None = None
    # An already-filed volamos-side issue this entry's FAIL is tracked
    # by, for entries deliberately left as a visible FAIL rather than
    # moved into KNOWN_DIVERGENCES (a real, unfixed volamos bug --
    # KNOWN_DIVERGENCES is reserved for vamos's own divergences). Purely
    # informational: printed alongside the FAIL, doesn't suppress it.
    tracking_issue: str | None = None


def setup_dos_match(tmpdir: Path) -> list[str]:
    """A scratch `SYS:` with the exact `c`/`devs`/`libs`/`s`/`t`
    skeleton `test/suite/dos_match.py`'s own expected output assumes --
    supplied explicitly (not relying on either engine's own `SYS:`
    defaults, which no longer agree with each other -- see the module
    doc)."""
    sys_dir = tmpdir / "sys"
    for name in ("c", "devs", "libs", "s", "t"):
        (sys_dir / name).mkdir(parents=True)
    return ["-V", f"SYS:{sys_dir}"]


def setup_dos_seek(tmpdir: Path) -> list[str]:
    """A scratch `TEST:` volume -- `dos_seek` creates its own file
    (`Open(..., MODE_NEWFILE)`), so nothing needs to pre-exist inside
    it."""
    test_dir = tmpdir / "test"
    test_dir.mkdir()
    return ["-V", f"TEST:{test_dir}"]


CORPUS = [
    Entry(
        name="dos_match",
        guest_args=["sys:"],
        setup=setup_dos_match,
        # Verbatim from test/suite/dos_match.py's own assertion -- the
        # two "sys: sys:" rows (ap_Flags 5 then 9) are a real, subtle
        # AnchorPath quirk (APF_DOWILD|APF_DODIR re-reports the scanned
        # directory itself once more on the way back out of its
        # descent), not a typo; this entry exists specifically to
        # exercise that.
        expected=[
            "sys: sys: 0 5",
            "c sys:c 0 1",
            "devs sys:devs 0 1",
            "libs sys:libs 0 1",
            "s sys:s 0 1",
            "t sys:t 0 1",
            "sys: sys: 0 9",
        ],
        tracking_issue="https://github.com/sidick/volamos/issues/46",
    ),
    Entry(
        name="dos_seek",
        guest_args=["TEST:test"],
        setup=setup_dos_seek,
        expected=[
            "old_pos=14, io_err=0, num_read=5, buf='Hello'",
            "old_pos=5, io_err=0, num_read=5, buf='rld!?'",
            "old_pos=14, io_err=219",
        ],
        tracking_issue="https://github.com/sidick/volamos/issues/47",
    ),
    Entry(name="util_date", guest_args=[], setup=None, data_file="util_date.txt"),
    Entry(name="vprintf", guest_args=[], setup=None, data_file="vprintf.txt"),
    Entry(
        name="exec_rawdofmt",
        guest_args=[],
        setup=None,
        data_file="exec_rawdofmt.txt",
        tracking_issue="https://github.com/sidick/volamos/issues/45",
    ),
]


def run_one(
    binary: list[str], extra_flags: list[str], program_path: Path, guest_args: list[str]
) -> tuple[str, int]:
    cmd = [*binary, *extra_flags, str(program_path), *guest_args]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.stdout, result.returncode


def load_data_file(checkout: Path, name: str) -> list[str]:
    path = checkout / "test" / "data" / name
    with path.open() as f:
        return [line.rstrip("\n") for line in f]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--amitools-checkout",
        required=True,
        help="path to a local amitools checkout with a built test/bin corpus "
        "(e.g. ~/src/amitools) -- never fetched or copied by this script",
    )
    parser.add_argument(
        "--volamos",
        default=str(REPO_ROOT / "target" / "release" / "volamos"),
        help="path to the volamos binary (default: target/release/volamos)",
    )
    parser.add_argument(
        "--vamos",
        default="vamos",
        help="path to the vamos binary (default: 'vamos' on $PATH)",
    )
    args = parser.parse_args()

    checkout = Path(args.amitools_checkout).expanduser().resolve()
    bin_dir = checkout / "test" / "bin"
    if not bin_dir.is_dir():
        print(f"error: {bin_dir} not found -- is --amitools-checkout correct?", file=sys.stderr)
        return 2

    results = []  # (name, status, detail)
    for entry in CORPUS:
        program = bin_dir / f"{entry.name}_{FLAVOR}"
        if not program.exists():
            results.append((entry.name, "SKIP", f"{program} not found"))
            continue

        with tempfile.TemporaryDirectory(prefix=f"compare-amitools-{entry.name}-") as tmp:
            extra = entry.setup(Path(tmp)) if entry.setup else []
            vol_stdout, vol_code = run_one([args.volamos], extra, program, entry.guest_args)
        with tempfile.TemporaryDirectory(prefix=f"compare-amitools-{entry.name}-") as tmp:
            extra = entry.setup(Path(tmp)) if entry.setup else []
            vam_stdout, vam_code = run_one(
                [args.vamos, "-q"], extra, program, entry.guest_args
            )

        vol_lines = vol_stdout.splitlines()
        vam_lines = vam_stdout.splitlines()

        ground_truth = entry.expected
        if ground_truth is None and entry.data_file is not None:
            ground_truth = load_data_file(checkout, entry.data_file)

        mismatches = []
        if vol_lines != vam_lines or vol_code != vam_code:
            mismatches.append(
                f"volamos vs vamos differ: volamos={vol_lines!r} exit={vol_code} "
                f"vamos={vam_lines!r} exit={vam_code}"
            )
        if ground_truth is not None:
            if vol_lines != ground_truth:
                mismatches.append(f"volamos vs ground truth: {vol_lines!r} != {ground_truth!r}")
            if vam_lines != ground_truth:
                mismatches.append(f"vamos vs ground truth: {vam_lines!r} != {ground_truth!r}")

        if not mismatches:
            results.append((entry.name, "PASS", ""))
        elif entry.name in KNOWN_DIVERGENCES:
            reason, issue = KNOWN_DIVERGENCES[entry.name]
            results.append((entry.name, "KNOWN", f"{reason} ({issue})"))
        else:
            detail = "; ".join(mismatches)
            if entry.tracking_issue:
                detail += f" [tracked: {entry.tracking_issue}]"
            results.append((entry.name, "FAIL", detail))

    width = max(len(name) for name, _, _ in results)
    for name, status, detail in results:
        line = f"{name:<{width}}  {status}"
        if detail:
            line += f"  -- {detail}"
        print(line)

    failed = [r for r in results if r[1] == "FAIL"]
    if failed:
        # "FAIL" (as opposed to KNOWN_DIVERGENCES) means an unfixed
        # volamos-side bug, not "nobody knows about this yet" -- an
        # entry can (and, right now, mostly does) have both a FAIL
        # status and a [tracked: ...] issue link at the same time; the
        # exit code stays non-zero either way until it's actually fixed.
        print(f"\n{len(failed)} divergence(s) attributed to volamos", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
