#!/usr/bin/env python3
"""Compares volamos against `vamos` using amitools' *own* test corpus
(`test/bin`/`test/suite`/`test/data` in an external amitools checkout,
e.g. `~/src/amitools`), rather than volamos's own hand-written fixtures
(that's `tools/compare_vamos.py`).

## Why a separate corpus from `compare_vamos.py`

amitools ships ~40 small real C programs, each pre-built with up to
four real Amiga compilers (`test/bin/<name>_<flavor>[_dbg]`: gcc, SAS/C
(`sc`), vbcc (`vc`), agcc), a `pytest` suite (`test/suite/*.py`) pinning
down each one's exact invocation and expected output, and checked-in
ground-truth output files (`test/data/*.txt`) for several. Multiple
real compilers' differing startup/calling conventions have found real
bugs in this project before (the `exectest` A6-convention issue --
`docs/plan.md`), so this is a meaningfully different, larger corpus
than volamos's own ~6 fixtures, not just more of the same.

## Licensing: local-only, external checkout, never bundled

amitools is GPLv2; volamos is MIT/Apache-2.0. Nothing under `test/src`,
`test/bin`, or `test/data` is ever copied into this repo -- `--amitools-checkout`
must point at an already-existing local checkout (there is no default;
unlike `--volamos`'s own `target/release/volamos`, there's no sensible
default for an external GPL checkout). Same posture
`tools/compare_three_way.py` already uses for its own external,
never-bundled assets (a proprietary AmiBake corpus and a Kickstart ROM
image) -- see that script's own module doc. This script is local-only
for the same reason: promoting it into CI (`tools/compare_vamos.py`'s
own `compare` job) is a plausible, separate future step once the
initial entries below are proven, not part of this first cut.

## Explicit, identical volume config per entry -- not either engine's
## own defaults

volamos (since issue #43) and `vamos`'s own test suite (via its
`test.vamosrc`) each install a *different* default `sys:` skeleton by
design -- `vamos`'s test suite assigns `sys:` to its own `ram:` auto-
volume, producing `c`/`s`/`libs`/`devs`/`t` subdirectories through
`vamos`'s own auto-assign machinery; volamos's own defaults produce a
persistent `SYS:` with `envarc`/`env` added and `t` living under `RAM:`
instead. Reconciling those two independent "zero-config" mechanisms
isn't the point of this harness -- each `CORPUS` entry instead supplies
the *same* explicit `-V`/`-a` flags to both engines, sidestepping
either side's own defaults entirely.

## Usage

    python3 tools/compare_amitools_suite.py --amitools-checkout ~/src/amitools

Exits non-zero if any corpus entry not fully explained by
`KNOWN_DIVERGENCES` disagrees between volamos and `vamos`, or (for an
entry with a `test/data/*.txt` ground-truth file) if either engine
disagrees with that checked-in expected output -- a stronger check than
two-engine agreement alone, which would miss a bug both sides happen to
share. **Caveat**: amitools' own `test/data/*.txt` files are themselves
generated by capturing a `vamos` run (`test/helper/runner.py`'s
`--gen-data` mode), not independently verified against real hardware --
so for a case where volamos and `vamos` disagree and the `.txt` file
sides with `vamos`, that's still really just "agrees with vamos", one
data point, not two.

## Corpus (14 entries so far; see this module's own "explicitly
## deferred" note in `docs/plan.md`'s matching entry for what's
## intentionally not here yet -- companion-binary-building entries,
## other compiler flavors, and CI promotion)

Multiple runs against this corpus have found and fixed eight real
volamos bugs (issues #45, #46, #47, #48, #51, #53, #55 -- #45,
`RawDoFmt`'s `%b` never converting its `BPTR` argument to a real
address; #46, `AnchorPath`'s `ap_Buf` always stripping the caller's own
device prefix instead of tracking whatever qualification level the
caller's own pattern text had; #47, `Seek()` never rejecting a target
position beyond EOF; #48, `%x`/`%lx` hex digit case; #51,
`IEEEDPCeil()`'s negative-zero sign; #53, `mathffp.library`/
`mathtrans.library`'s FFP sign/exponent bits swapped plus wrong
overflow/underflow saturation; #55, `dos.library/FindArg` not
implemented at all -- confirmed correct against real Kickstart 3.1
hardware via Copperline (A600 model, for Gayle IDE support, and for
#46 specifically, a genuine in-memory FFS synthesized from a host
directory via `[ide]`, not just `--run`'s convenience mount, after an
initial `--run`-based fix attempt caused a direct, reproducible
regression in volamos's own `Delete` -- see issue #46's own comment
thread for the full story), one further, narrower gap surfaced by
fixing #46 (issue #58, `MatchFirst`'s volume-root `fib_FileName`/
`APF_DirChanged` flags), and two divergences confirmed attributed to
`vamos` itself via the same real-hardware verification (#49, `CheckDate`
wday; #52, qNaN sign bit for domain-error results) -- concrete evidence
this corpus finds things volamos's own ~6 fixtures don't. `dos_match`
(#58) and `math_fast_trans` (#53's own residual 1-ULP transcendental
noise) are the only entries still a tracked `FAIL` below.

- `dos_match`: `MatchFirst`/`MatchNext`/`ap_Buf` via a real `AnchorPath`
  scan of a scratch `SYS:` -- exercises `crate::dosanchor`.
- `dos_seek`: `Open(MODE_NEWFILE)`/`Write`/`Seek`/`Read`/`IoErr` round
  trip against a scratch `TEST:` volume -- fully self-contained (the
  program creates its own file).
- `dos_examine`: `Lock`/`Examine`/`ExNext` against a scratch `TEST:`
  subdirectory (order-tolerant, matching `test/suite/dos_examine.py`'s
  own "either ExNext order" acceptance).
- `dos_findarg`: `dos.library/FindArg` -- implemented (#55, fixed).
- `util_date`, `vprintf`, `exec_rawdofmt`, `dos_stdout`, `util_muldiv`,
  `exec_copymem`, `math_double`, `math_double_trans`, `math_fast`,
  `math_fast_trans`: no volume needed at all; the `math_*`/`util_date`/
  `vprintf`/`exec_rawdofmt` entries compare three-way against their
  checked-in `test/data/*.txt`.

Explicitly **not** added despite being self-contained: `test_hello`/
`test_raise` (they call `vamostest.library`, a `vamos`-only internal
testing/debugging library with no real-AmigaOS counterpart -- there is
nothing for volamos to implement here, this isn't a gap) and
`exec_initstruct` (`InitStruct()`'s byte-code interpreter is a real
gap, but volamos's own `execlib.rs` already documents it as deferred
to a later phase -- not a quick add) and `math_single`/
`math_single_trans` (need `mathieeesingbas.library`/
`mathieeesingtrans.library`, which volamos doesn't implement at all;
same "real gap, not a quick add" reasoning).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

REPO_ROOT = Path(__file__).resolve().parent.parent

FLAVOR = "gcc"

# fixture (corpus-entry) name -> (reason, issue URL). Same convention as
# compare_vamos.py's KNOWN_DIVERGENCES -- reserved for divergences
# attributed to vamos (or genuinely unresolved pending real-hardware
# verification), never for volamos's own unfixed bugs, which should stay
# visible FAILs until fixed (see dos_match/exec_rawdofmt below, each
# with its own open volamos-side issue).
KNOWN_DIVERGENCES: dict[str, tuple[str, str]] = {
    "dos_seek": (
        "Seek()'s own NDK autodoc BUGS note: pre-V39 filesystems "
        "returned the *current* position instead of -1 when a Seek() "
        "target landed beyond EOF, fixed in V39. volamos (target: "
        "KS/WB 3.1, V40) now rejects the out-of-range Seek() (issue "
        "#47, fixed) and correctly returns -1/ERROR_SEEK_ERROR; vamos's "
        "old_pos=14 still reproduces the old, documented-as-fixed "
        "pre-V39 behavior -- it's a hardcoded assertion in vamos's own "
        "pytest suite, not real V39+/V40 hardware.",
        "https://github.com/sidick/volamos/issues/47",
    ),
    "util_date": (
        "utility.library/CheckDate's own NDK autodoc documents 'the wday "
        "field ... is not checked' as a real historical AmigaOS bug -- "
        "volamos matches that; vamos validates wday anyway. Also affected "
        "by the %x hex-digit-case question below.",
        "https://github.com/sidick/volamos/issues/49",
    ),
    "vprintf": (
        "%x/%lx hex digit case: confirmed via real Kickstart 3.1 "
        "hardware (Copperline, A600/Gayle) that uppercase is correct; "
        "volamos fixed to match. util_date and the math_* entries below "
        "were also affected by this same bug and are now clean of it -- "
        "kept here only because vamos's own captured `%x` output in "
        "this particular corpus predates volamos's fix and vamos itself "
        "isn't being changed.",
        "https://github.com/sidick/volamos/issues/48",
    ),
    "dos_stdout": (
        "WriteChars(msg, sizeof(msg)) legitimately includes the trailing "
        "NUL sizeof() adds for a string-literal-initialized array; "
        "WriteChars's own NDK autodoc documents a plain raw byte-count "
        "write with no NUL special-casing. volamos writes it verbatim; "
        "vamos's captured output drops everything from the NUL onward.",
        "https://github.com/sidick/volamos/issues/54",
    ),
    "math_double": (
        "Down to a single remaining question: qNaN sign bit for "
        "domain-error results (div0/div1). Confirmed via real Kickstart "
        "3.1 hardware (Copperline, A600/Gayle) that a positive-signed "
        "NaN ($7FF8...) is correct -- volamos already matches; vamos's "
        "negative-signed ($FFF8...) is vamos's own divergence, not a "
        "volamos bug. The %x hex-case (#48) and IEEEDPCeil "
        "negative-zero (#51, was actually a real volamos bug -- fixed) "
        "issues that used to also show up here are both resolved.",
        "https://github.com/sidick/volamos/issues/48, "
        "https://github.com/sidick/volamos/issues/51, "
        "https://github.com/sidick/volamos/issues/52",
    ),
    "math_double_trans": (
        "Same NaN sign-bit question as math_double's div0/div1 (#52), "
        "here in acos/asin/log's domain-error results -- confirmed via "
        "real Kickstart 3.1 hardware that volamos's positive sign is "
        "correct and vamos's negative sign is vamos's own divergence.",
        "https://github.com/sidick/volamos/issues/48, "
        "https://github.com/sidick/volamos/issues/52",
    ),
}


@dataclass
class Entry:
    name: str
    guest_args: list[str]
    # Returns the extra -V/-a flags (identical for both engines) this
    # entry needs, given a fresh scratch directory; None if the entry
    # needs no volume/assign at all.
    setup: Callable[[Path], list[str]] | None
    # Exact expected stdout lines (order matters, no normalization
    # applied) when known ahead of time from test/suite/<name>.py
    # itself; None when comparison instead reads test/data/<name>.txt
    # (see `data_file`).
    expected: list[str] | None = None
    # Basename of a checked-in ground-truth file under test/data/, for
    # a three-way comparison instead of (or in addition to) `expected`.
    data_file: str | None = None
    # An already-filed volamos-side issue this entry's FAIL is tracked
    # by, for entries deliberately left as a visible FAIL rather than
    # moved into KNOWN_DIVERGENCES (a real, unfixed volamos bug --
    # KNOWN_DIVERGENCES is reserved for vamos's own divergences). Purely
    # informational: printed alongside the FAIL, doesn't suppress it.
    tracking_issue: str | None = None
    # Applied to volamos's, vamos's, and `expected`'s own line lists
    # before comparing -- for output whose real AmigaOS ordering isn't
    # guaranteed (e.g. an ExNext directory listing), matching
    # compare_vamos.py's own `dirtest` normalization. `None` (the
    # default) compares lines exactly as produced, in order.
    normalize: Callable[[list[str]], list[str]] | None = None


def setup_dos_match(tmpdir: Path) -> list[str]:
    """A scratch `SYS:` with the exact `c`/`devs`/`libs`/`s`/`t`
    skeleton `test/suite/dos_match.py`'s own expected output assumes --
    supplied explicitly (not relying on either engine's own `SYS:`
    defaults, which no longer agree with each other -- see the module
    doc)."""
    sys_dir = tmpdir / "sys"
    for name in ("c", "devs", "libs", "s", "t"):
        (sys_dir / name).mkdir(parents=True)
    return ["-V", f"SYS:{sys_dir}"]


def setup_dos_examine(tmpdir: Path) -> list[str]:
    """A scratch `TEST:` volume with a `bla` subdirectory containing
    exactly `test/suite/dos_examine.py`'s own fixture: a 14-byte file
    `foo` ("hello, world!\\n") and an empty directory `bar` -- `bla`
    itself (not the volume root) is what gets Locked/Examined, so
    `fib_FileName` reports "bla", matching the real test's own
    expectation."""
    bla = tmpdir / "bla"
    bla.mkdir()
    (bla / "foo").write_text("hello, world!\n")
    (bla / "bar").mkdir()
    return ["-V", f"TEST:{tmpdir}"]


def setup_dos_seek(tmpdir: Path) -> list[str]:
    """A scratch `TEST:` volume -- `dos_seek` creates its own file
    (`Open(..., MODE_NEWFILE)`), so nothing needs to pre-exist inside
    it."""
    test_dir = tmpdir / "test"
    test_dir.mkdir()
    return ["-V", f"TEST:{test_dir}"]


CORPUS = [
    Entry(
        name="dos_match",
        guest_args=["sys:"],
        setup=setup_dos_match,
        # Verbatim from test/suite/dos_match.py's own assertion -- the
        # two "sys: sys:" rows (ap_Flags 5 then 9) are a real, subtle
        # AnchorPath quirk (APF_DOWILD|APF_DODIR re-reports the scanned
        # directory itself once more on the way back out of its
        # descent), not a typo; this entry exists specifically to
        # exercise that.
        #
        # ap_Buf's own device-prefix question (originally issue #46) is
        # fixed and confirmed via real Kickstart 3.1 hardware -- every
        # ap_Buf column now matches vamos's exactly. The residual
        # mismatch is narrower: the volume-root rows' fib_FileName
        # ("SYS"/empty first column) and the ap_Flags values on the
        # "c" and final rows -- see issue #58 (fib_FileName confirmed
        # via real hardware to want blank; the ap_Flags/APF_DirChanged
        # question is still unconfirmed either way).
        expected=[
            "sys: sys: 0 5",
            "c sys:c 0 1",
            "devs sys:devs 0 1",
            "libs sys:libs 0 1",
            "s sys:s 0 1",
            "t sys:t 0 1",
            "sys: sys: 0 9",
        ],
        tracking_issue="https://github.com/sidick/volamos/issues/58",
    ),
    Entry(
        name="dos_seek",
        guest_args=["TEST:test"],
        setup=setup_dos_seek,
        # `Seek()`'s own NDK autodoc BUGS note: pre-V39 filesystems
        # returned the *current* position instead of `-1` when a Seek()
        # target lands beyond EOF; fixed in V39. This literal ground
        # truth (and vamos's own output) still reproduces that old,
        # documented-as-fixed behavior -- it's a hardcoded assertion in
        # vamos's own pytest suite, not real hardware. volamos (target:
        # KS/WB 3.1, V40) now correctly rejects the out-of-range Seek()
        # (issue #47) and returns the modern `-1`/`ERROR_SEEK_ERROR`
        # instead of the old pre-V39 position -- see KNOWN_DIVERGENCES.
        expected=[
            "old_pos=14, io_err=0, num_read=5, buf='Hello'",
            "old_pos=5, io_err=0, num_read=5, buf='rld!?'",
            "old_pos=14, io_err=219",
        ],
        tracking_issue="https://github.com/sidick/volamos/issues/47",
    ),
    Entry(name="util_date", guest_args=[], setup=None, data_file="util_date.txt"),
    Entry(name="vprintf", guest_args=[], setup=None, data_file="vprintf.txt"),
    Entry(
        name="exec_rawdofmt",
        guest_args=[],
        setup=None,
        data_file="exec_rawdofmt.txt",
        tracking_issue="https://github.com/sidick/volamos/issues/45",
    ),
    Entry(
        name="dos_examine",
        guest_args=["TEST:bla"],
        setup=setup_dos_examine,
        # test/suite/dos_examine.py itself accepts either ExNext order
        # ("foo then bar" or "bar then foo" -- real AmigaOS ExNext
        # ordering isn't guaranteed), so this is compared sorted, same
        # normalization compare_vamos.py's own dirtest entry uses.
        expected=["Examine: bla", "   14 foo", "<DIR> bar", "ok"],
        normalize=sorted,
    ),
    Entry(
        name="dos_findarg",
        guest_args=[],
        setup=None,
        # dos.library/FindArg's own NDK autodoc confirms these are the
        # real, documented results (abbreviation/multi-keyword lookup
        # in a ReadArgs-style template) -- not just "whatever this test
        # happened to observe". Implemented (#55, fixed) on top of
        # dosargs.rs's existing ReadArgs template parser.
        expected=[
            "FindArg(a=b/k,a)=0  == 0  ok",
            "FindArg(a=b/k,b)=0  == 0  ok",
            "FindArg(a=b/k,c)=-1  == -1  ok",
            "FindArg(hello/k,world/m,world)=1  == 1  ok",
        ],
        tracking_issue="https://github.com/sidick/volamos/issues/55",
    ),
    Entry(
        name="dos_stdout",
        guest_args=[],
        setup=None,
        expected=["Hello, world!?", "Hello, world!?"],
    ),
    Entry(name="util_muldiv", guest_args=[], setup=None, data_file="util_muldiv.txt"),
    Entry(name="exec_copymem", guest_args=[], setup=None, expected=[]),
    Entry(name="math_double", guest_args=[], setup=None, data_file="math_double.txt"),
    Entry(
        name="math_double_trans",
        guest_args=[],
        setup=None,
        data_file="math_double_trans.txt",
    ),
    Entry(
        name="math_fast",
        guest_args=[],
        setup=None,
        data_file="math_fast.txt",
        # Was far more than hex-case noise (~50 of 84 lines differed in
        # actual value) until issue #53's root cause -- ffp_to_f32/
        # f32_to_ffp had the sign bit and exponent field swapped -- was
        # fixed. The mul3/mul4 overflow-saturation boundary case (at
        # exactly FFP's max exponent field) was confirmed via real
        # Kickstart 3.1 hardware (Copperline) to already-saturate, and
        # f32_to_ffp's `>= 127` fix matches that. Fully PASSing now;
        # tracking_issue kept only as a pointer back to #53's history,
        # it has no effect once there are no mismatches to report.
        tracking_issue="https://github.com/sidick/volamos/issues/53",
    ),
    Entry(
        name="math_fast_trans",
        guest_args=[],
        setup=None,
        data_file="math_fast_trans.txt",
        # Same #53 fix took this from ~110 of 149 lines differing to 5
        # -- all tiny (1-ULP-ish) mantissa differences in acos/asin/
        # atan results, consistent with ordinary cross-implementation
        # transcendental-function rounding variance rather than a bug
        # (real hardware wasn't chased for this specific residual --
        # sub-ULP transcendental rounding is expected to vary across
        # any two independent math library implementations).
        tracking_issue="https://github.com/sidick/volamos/issues/53",
    ),
]


def run_one(
    binary: list[str], extra_flags: list[str], program_path: Path, guest_args: list[str]
) -> tuple[str, int]:
    cmd = [*binary, *extra_flags, str(program_path), *guest_args]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return result.stdout, result.returncode


def load_data_file(checkout: Path, name: str) -> list[str]:
    path = checkout / "test" / "data" / name
    with path.open() as f:
        return [line.rstrip("\n") for line in f]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--amitools-checkout",
        required=True,
        help="path to a local amitools checkout with a built test/bin corpus "
        "(e.g. ~/src/amitools) -- never fetched or copied by this script",
    )
    parser.add_argument(
        "--volamos",
        default=str(REPO_ROOT / "target" / "release" / "volamos"),
        help="path to the volamos binary (default: target/release/volamos)",
    )
    parser.add_argument(
        "--vamos",
        default="vamos",
        help="path to the vamos binary (default: 'vamos' on $PATH)",
    )
    args = parser.parse_args()

    checkout = Path(args.amitools_checkout).expanduser().resolve()
    bin_dir = checkout / "test" / "bin"
    if not bin_dir.is_dir():
        print(f"error: {bin_dir} not found -- is --amitools-checkout correct?", file=sys.stderr)
        return 2

    results = []  # (name, status, detail)
    for entry in CORPUS:
        program = bin_dir / f"{entry.name}_{FLAVOR}"
        if not program.exists():
            results.append((entry.name, "SKIP", f"{program} not found"))
            continue

        with tempfile.TemporaryDirectory(prefix=f"compare-amitools-{entry.name}-") as tmp:
            extra = entry.setup(Path(tmp)) if entry.setup else []
            vol_stdout, vol_code = run_one([args.volamos], extra, program, entry.guest_args)
        with tempfile.TemporaryDirectory(prefix=f"compare-amitools-{entry.name}-") as tmp:
            extra = entry.setup(Path(tmp)) if entry.setup else []
            vam_stdout, vam_code = run_one(
                [args.vamos, "-q"], extra, program, entry.guest_args
            )

        vol_lines = vol_stdout.splitlines()
        vam_lines = vam_stdout.splitlines()

        ground_truth = entry.expected
        if ground_truth is None and entry.data_file is not None:
            ground_truth = load_data_file(checkout, entry.data_file)

        if entry.normalize is not None:
            vol_lines = entry.normalize(vol_lines)
            vam_lines = entry.normalize(vam_lines)
            if ground_truth is not None:
                ground_truth = entry.normalize(ground_truth)

        mismatches = []
        if vol_lines != vam_lines or vol_code != vam_code:
            mismatches.append(
                f"volamos vs vamos differ: volamos={vol_lines!r} exit={vol_code} "
                f"vamos={vam_lines!r} exit={vam_code}"
            )
        if ground_truth is not None:
            if vol_lines != ground_truth:
                mismatches.append(f"volamos vs ground truth: {vol_lines!r} != {ground_truth!r}")
            if vam_lines != ground_truth:
                mismatches.append(f"vamos vs ground truth: {vam_lines!r} != {ground_truth!r}")

        if not mismatches:
            results.append((entry.name, "PASS", ""))
        elif entry.name in KNOWN_DIVERGENCES:
            reason, issue = KNOWN_DIVERGENCES[entry.name]
            results.append((entry.name, "KNOWN", f"{reason} ({issue})"))
        else:
            detail = "; ".join(mismatches)
            if entry.tracking_issue:
                detail += f" [tracked: {entry.tracking_issue}]"
            results.append((entry.name, "FAIL", detail))

    width = max(len(name) for name, _, _ in results)
    for name, status, detail in results:
        line = f"{name:<{width}}  {status}"
        if detail:
            line += f"  -- {detail}"
        print(line)

    failed = [r for r in results if r[1] == "FAIL"]
    if failed:
        # "FAIL" (as opposed to KNOWN_DIVERGENCES) means an unfixed
        # volamos-side bug, not "nobody knows about this yet" -- an
        # entry can (and, right now, mostly does) have both a FAIL
        # status and a [tracked: ...] issue link at the same time; the
        # exit code stays non-zero either way until it's actually fixed.
        print(f"\n{len(failed)} divergence(s) attributed to volamos", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
